"""Update feeds

Revision ID: 2c252652296b
Revises: 
Create Date: 2024-10-24 09:49:00.093358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c252652296b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_feeds')
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.drop_column('animal_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('animal_name', sa.VARCHAR(), nullable=True))

    op.create_table('_alembic_tmp_feeds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('feed_type', sa.VARCHAR(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('animal_name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_feeds')
    )
    # ### end Alembic commands ###
